spring.application.name=core-service

spring.application.name=core-service
spring.datasource.url=jdbc:postgresql://localhost:5432/opsflow
spring.datasource.username=opsflow
spring.datasource.password=opsflow
spring.jpa.hibernate.ddl-auto=none